/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projetos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Projetos */
        get: operations["listar_projetos_projetos_get"];
        put?: never;
        /** Criar Projeto */
        post: operations["criar_projeto_projetos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hipoteses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Hipoteses */
        get: operations["listar_hipoteses_hipoteses_get"];
        put?: never;
        /** Criar Hipotese */
        post: operations["criar_hipotese_hipoteses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HipoteseCreate */
        HipoteseCreate: {
            /**
             * Projeto Id
             * @example 1
             */
            projeto_id: number;
            /**
             * Enunciado
             * @example Se o Copilot mostrar hipóteses já testadas, então a Marina não repetirá caminhos que já falharam, porque a decisão vem do histórico.
             */
            enunciado: string;
            /**
             * Metrica
             * @example Dias perdidos re-testando abordagens descartadas
             */
            metrica: string;
            /**
             * Baseline
             * @default
             * @example 2 a 4 dias por ocorrência
             */
            baseline: string;
            /**
             * Alvo
             * @default
             * @example menos de 1 dia
             */
            alvo: string;
            /**
             * Resultado
             * @default em_teste
             * @enum {string}
             */
            resultado: "em_teste" | "validada" | "refutada";
        };
        /** HipoteseOut */
        HipoteseOut: {
            /** Id */
            id: number;
            /** Projeto Id */
            projeto_id: number;
            /** Enunciado */
            enunciado: string;
            /** Metrica */
            metrica: string;
            /** Baseline */
            baseline: string;
            /** Alvo */
            alvo: string;
            /**
             * Resultado
             * @enum {string}
             */
            resultado: "em_teste" | "validada" | "refutada";
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
        };
        /** ProjetoCreate */
        ProjetoCreate: {
            /**
             * Nome
             * @example Paris Group Copilot
             */
            nome: string;
            /**
             * Descricao
             * @default
             * @example Registro de hipóteses testadas pelo studio
             */
            descricao: string;
        };
        /** ProjetoOut */
        ProjetoOut: {
            /** Id */
            id: number;
            /** Nome */
            nome: string;
            /** Descricao */
            descricao: string;
            /**
             * Criado Em
             * Format: date-time
             */
            criado_em: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    listar_projetos_projetos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjetoOut"][];
                };
            };
        };
    };
    criar_projeto_projetos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjetoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjetoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_hipoteses_hipoteses_get: {
        parameters: {
            query?: {
                projeto_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HipoteseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_hipotese_hipoteses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HipoteseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HipoteseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
